apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shop.yaml
  - analytics.yaml

# Sur deploy/prod, le CD remplace ces tags par le SHA du commit (images immuables).
images:
  - name: ghcr.io/sipixer/spire-devsecops/gateway
    newTag: latest
  - name: ghcr.io/sipixer/spire-devsecops/orders
    newTag: latest
  - name: ghcr.io/sipixer/spire-devsecops/catalog
    newTag: latest
  - name: ghcr.io/sipixer/spire-devsecops/payments
    newTag: latest
  - name: ghcr.io/sipixer/spire-devsecops/analytics
    newTag: latest
