---
- name: Repo Helm SPIFFE
  kubernetes.core.helm_repository:
    name: spiffe
    repo_url: "{{ spire_helm_repo }}"

- name: Namespace SPIRE
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ spire_namespace }}"
        labels:
          pod-security.kubernetes.io/enforce: privileged

- name: CRDs SPIRE
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: spire-crds
    chart_ref: spiffe/spire-crds
    chart_version: "{{ spire_crds_chart_version }}"
    release_namespace: "{{ spire_namespace }}"

- name: Values SPIRE
  ansible.builtin.template:
    src: spire-values.yaml.j2
    dest: /tmp/spire-values.yaml
    mode: "0644"

- name: Chart SPIRE (Server + Agent)
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: spire
    chart_ref: spiffe/spire
    chart_version: "{{ spire_chart_version }}"
    release_namespace: "{{ spire_namespace }}"
    values_files: [/tmp/spire-values.yaml]
    wait: true
    timeout: 5m0s
